-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 23:00:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UserBankList
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UserBankList
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UserBankList` DEFAULT CHARACTER SET utf8 ;
USE `UserBankList` ;

-- -----------------------------------------------------
-- Table `UserBankList`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserBankList`.`account` (
  `accountID` INT NOT NULL,
  `userID` INT NOT NULL AUTO_INCREMENT,
  `accountCurrency` VARCHAR(5) NOT NULL,
  `type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `cashback` INT NULL,
  `isRefundable` TINYINT NULL,
  `credit` INT NULL,
  `dateOfCreation` DATE NOT NULL,
  `dateOfExpiration` TIMESTAMP(8) NOT NULL,
  `balance` FLOAT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UserBankList`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserBankList`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sureName` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `telephone` VARCHAR(9) NOT NULL,
  `countryCode` VARCHAR(4) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `addressRegistration` VARCHAR(150) NOT NULL,
  `addressResidence` VARCHAR(150) NULL,
  `passportNo` VARCHAR(9) NOT NULL,
  `nationality` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`),
  CONSTRAINT `user`
    FOREIGN KEY (`userID`)
    REFERENCES `UserBankList`.`account` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
